### ISSUE TITLE
Validation Error for config file with Stdout

### ISSUE THREAD

**Issue by JWahle** [HEnquist/pycamilladsp-plot#4]
On the latest camillagui & backend `final050` branches,
when parsing [this config](https://github.com/HEnquist/pycamilladsp-plot/files/6417935/empty.yml.zip) I get the following error:
```
Traceback (most recent call last):
  File "/home/joe/.local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/home/joe/.local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/mnt/46730E141B4B08D7/Moode/camillagui-backend/backend/views.py", line 211, in get_config_file
    json_config = new_config_with_relative_filter_paths(get_yaml_as_json(request, config_file), config_dir)
  File "/mnt/46730E141B4B08D7/Moode/camillagui-backend/backend/filemanagement.py", line 76, in get_yaml_as_json
    validator.validate_file(path)
  File "/home/joe/.local/lib/python3.8/site-packages/camilladsp_plot/validate_config.py", line 126, in validate_file
    self._validate_config()
  File "/home/joe/.local/lib/python3.8/site-packages/camilladsp_plot/validate_config.py", line 149, in _validate_config
    self.validate_with_schemas()
  File "/home/joe/.local/lib/python3.8/site-packages/camilladsp_plot/validate_config.py", line 182, in validate_with_schemas
    playback_schema = self.playback_schemas[playback_type]
KeyError: 'Stdout'
```

I think, this config should be parseable - it is at least valid, when parsed by CDSP.

**Comment by HEnquist** [comment]
Typo here... https://github.com/HEnquist/pycamilladsp-plot/blob/master/camilladsp_plot/schemas/playback.json#L78
Sorry about that, will fix tomorrow!

**Comment by HEnquist** [comment]
Typo fixed!

**Comment by JWahle** [comment]
There is no exception thrown anymore, but now I get validation errors for the config from above (capture=stdin, playback=stdout):
devices/playback/type: 'Stdout' is not one of ['Stdin']
devices/capture: Additional properties are not allowed ('extra_samples' was unexpected) [This error is also shown for the `file` playback device]

**Comment by HEnquist** [comment]
I was too quick and only fixed half of it. I think it should be ok now.
